
workflows:
  android-workflow:
    name: Hadi Tasks Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - default
    scripts:
      - name: Get dependencies
        script: |
          flutter packages pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com # Put your email here to get a notification
